### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by FEA-eng** [nayem-cosmic/FEM-Plate-MZC-Python#2]
The code generates "ValueError: cannot reshape array of size 16 into shape (4,)" when trying to run plate_mzc.py with default plate data.

**Comment by nf-project** [comment]
Hi. This change needs to be done
" Strnod[lnods,0] = Strnod[lnods,0] + Str1"
to 
"Strnod[lnods,0] = Strnod.toarray()[lnods,0] + Str1[:,0]"

**Comment by aliznayem** [comment]
Thank you!
Can you create a pull request with the change?
